server:
  port: 8080

spring:
  application:
    name: createpayment-modulex-service
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: "yyyy-MM-dd'T'HH:mm:ss"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always

result-callback:
  enabled: false
  url: ""
  connect-timeout-ms: 5000
  read-timeout-ms: 15000
  max-attempts: 3
  retry-delay-ms: 5000

pgw:
  enabled: true
  url: https://ingress-pgw-4g-ift.https.dev-sh5.ocp-geo.delta.sbrf.ru
  transfer-path: /upd/transfer
  connect-timeout-ms: 5000
  read-timeout-ms: 30000
  max-attempts: 3
  retry-delay-ms: 30000

sber-integration:
  url: http://stmnt-http.apps.bcivthq2.k8s.delta.sbrf.ru/sberintegration-statement-server/execute
  method: getSberIntegration
  version: "1.0"
  connect-timeout-ms: 5000
  read-timeout-ms: 15000
  bic-directory: false

logging:
  level:
    ru.sbrf.pprb.stmnt.modulex: DEBUG
