server:
  port: 8080

spring:
  application:
    name: createpayment-modulex-service
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: "yyyy-MM-dd'T'HH:mm:ss"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always

sber-integration:
  url: http://stmnt-http.apps.bcivthq2.k8s.delta.sbrf.ru/sberintegration-statement-server/execute
  method: getSberIntegration
  version: "1.0"
  connect-timeout-ms: 5000
  read-timeout-ms: 15000
  bic-directory: false

logging:
  level:
    ru.sbrf.pprb.stmnt.modulex: DEBUG
