server:
  port: 8080

spring:
  application:
    name: createpayment-modulex-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always

createpayment:
  max-amount: 100000000
  min-amount: 0.01
  default-currency: "810"
  purpose-max-length: 210

ignite:
  thin-client:
    enabled: false
    addresses:
      - 127.0.0.1:10800
    connect-timeout-ms: 5000
    cache-name: payments

logging:
  level:
    ru.sbrf.pprb.stmnt.modulex: DEBUG
